### ISSUE TITLE
missing code for "MetaAlign: Coordinating Domain Alignment and Classification for Unsupervised Domain Adaptation"

### ISSUE THREAD

**Issue by jingzhengli** [microsoft/UDA#4]
Thanks for the nice works. It seems to be no code for this paper "MetaAlign: Coordinating Domain Alignment and Classification for Unsupervised Domain Adaptation".

**Comment by hvingelby** [comment]
To my knowledge there is still no code for the MetaAlign paper. Why was this issue closed @jingzhengli? 🙂

**Comment by surya1701** [comment]
> To my knowledge there is still no code for the MetaAlign paper. Why was this issue closed @jingzhengli? 🙂 

Any updates on this? @jingzhengli @hvingelby

**Comment by hvingelby** [comment]
I have not heard any updates on this.
